-- Run once in VIBE_CODE_DB (or your chosen database).
-- Set SNOWFLAKE_SCHEMA=LLMS_TXT in .env to match.

CREATE SCHEMA IF NOT EXISTS LLMS_TXT;

CREATE TABLE IF NOT EXISTS LLMS_TXT.LLMSTXT_CONFIGS (
    DOMAIN VARCHAR(255) NOT NULL PRIMARY KEY,
    CONFIG VARIANT NOT NULL,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
